### ISSUE TITLE
Unable to open MDANSE after installation

### ISSUE THREAD

**Issue by braunewell** [ISISNeutronMuon/MDANSE#129]
I have installed mdanse on my ubuntu (22.04), however, when trying to open the application it runs the following messages and does not open anything:

balthasar@Fulmen:~$ mdanse
ERROR:root:code for hash md5 was not found.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/usr/local/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type md5
ERROR:root:code for hash sha1 was not found.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/usr/local/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha1
ERROR:root:code for hash sha224 was not found.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/usr/local/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha224
ERROR:root:code for hash sha256 was not found.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/usr/local/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha256
ERROR:root:code for hash sha384 was not found.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/usr/local/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha384
ERROR:root:code for hash sha512 was not found.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/usr/local/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha512

Best wishes,
Balthasar

**Comment by RastislavTuranyi** [comment]
Hi Balthasar, this seems like an issue with OpenSSL. How did you install MDANSE, and what is your version of OpenSSL? If you used the Ubuntu20 or Ubuntu21 installer that we provide, then I suspect that the issue lies in that MDANSE was built with a different version of OpenSSL (1.1.1) than the one you have (probably 3, I believe). 

I don't have any fix at hand other than building from source, but I'll download a Ubuntu 22 image and investigate. I'll also look into adding Ubuntu 22 to the CI/CD and let you know if I find a fix.

**Comment by RastislavTuranyi** [comment]
@braunewell, I have created a new CI/CD pipeline for generating installers for Ubuntu 22.04. The installer is in [this run](https://github.com/ISISNeutronMuon/MDANSE/actions/runs/2624053244) and works on my VM, but please let me know if there are any issues.

**Comment by braunewell** [comment]
Hi Rastislav,

Sorry for the late reply and many thanks for looking into my issue for me :)

I'll give it a shot and let you know!

Best wishes,
Balthasar

**Comment by braunewell** [comment]
This installer works,

Thanks a bunch, Rastislav!

Best wishes,
Balthasar
