### ISSUE TITLE
Unable to import AtomSelectionParser

### ISSUE THREAD

**Issue by MBartkowiakSTFC** [ISISNeutronMuon/MDANSE#210]
If I try to import AtomSelectionParser
`from MDANSE.Framework.AtomSelectionParser import AtomSelectionParser`
I immediately get an error:
```
Traceback (most recent call last):
  File "/Users/maciej.bartkowiak/science/fake-data-for-MDMC/new_mdanse/analysis_script_python3.py", line 12, in <module>
    from MDANSE.Framework.AtomSelectionParser import AtomSelectionParser
  File "/Users/maciej.bartkowiak/python/builder/lib/python3.11/site-packages/MDANSE/Framework/AtomSelectionParser.py", line 20, in <module>
    from MDANSE.Externals.pyparsing.pyparsing import delimitedList, oneOf, opAssoc, operatorPrecedence, printables, Forward, OneOrMore, Optional, Word
  File "/Users/maciej.bartkowiak/python/builder/lib/python3.11/site-packages/MDANSE/Externals/pyparsing/pyparsing.py", line 110, in <module>
    range = xrange
            ^^^^^^
NameError: name 'xrange' is not defined. Did you mean: 'range'?
```

The code included in Externals/pyparsing is most likely seriously outdated. The main question is whether to try to fix it, or just to get rid of it altogether. I am hoping that pyparsing was included in the code because some feature was missing in Python 2 at the time, and we can replace it with something from the standard library now.

**Comment by MBartkowiakSTFC** [comment]
It looks like the `Externals.pyparsing` can be replaced by the up-to-date `pyparsing` module from pypi. The structure of the modules has changed a little, but it will not require too complex changes.

**Comment by MBartkowiakSTFC** [comment]
While it was possible to get pyparsing to work in the protos branch, it would be the best to come up with a more stable method of selecting atoms.

The criteria are:
1. Inputs should be general enough to be transferred from one trajectory file to another (e.g. "Pick all oxygen atoms", "Pick all water molecules"),
2. There should be operators combining the selections (e.g. "Pick all oxygen atoms that are NOT in water molecules"),
3. The result should be a list of atom indices.
4. The default selection should be all the atoms in the trajectory.
