### ISSUE TITLE
BUG: Normalisation does not work with GACF and PACF

### ISSUE THREAD

**Issue by RastislavTuranyi** [ISISNeutronMuon/MDANSE#22]
Attempting to run general autocorrelation function or position autocorrelation function with the 'Normalise' box ticked results in job failure with the following traceback:

```
Traceback (most recent call last):
  File "C:\Program Files\MDANSE\lib\site-packages\MDANSE\Framework\Jobs\IJob.py", line 319, in run
    self.finalize()
  File "C:\Program Files\MDANSE\lib\site-packages\MDANSE\Framework\Jobs\GeneralAutoCorrelationFunction.py", line 112, in finalize
    for element in self.configuration['atom_selection']['n_atoms_per_element'].keys():
KeyError: 'n_atoms_per_element'
```

However, normalisation works with VACF.

Furthermore, only when this bug is encountered in GACF, starting any analysis afterwards causes it not to show up in the Jobs tab unless it fails. If it fails, it does show up as normal, though only after it fails, but otherwise there are no issues with it. However, if the analysis does succeed, it does not show up in the Jobs tab at all, while the output file is created. Restarting MDANSE fixes this display issue.

**Comment by RastislavTuranyi** [comment]
This bug can be resolved very easily in either of two ways:

1. The call to `self.configuration['atom_selection']['n_atoms_per_element']` which does not exist is replaced with `nAtomsPerElement` which is calculated just above, resulting in the problematic for loop statement being `for element in nAtomsPerElement.keys():`. This is the way in which normalisation is done in VACF.
2. `self.configuration['atom_selection']['n_atoms_per_element']` is created prior to the for loop by running `self.configuration['atom_selection']['n_atoms_per_element'] = nAtomsPerElement`
