### ISSUE TITLE
[BUG] pip installation directly from GitHub not possible

### ISSUE THREAD

**Issue by MBartkowiakSTFC** [ISISNeutronMuon/MDANSE#248]
**Description of the error**
Ideally, the command
`python3 -m pip install  "git+https://github.com/ISISNeutronMuon/MDANSE@protos#egg=MDANSE&subdirectory=MDANSE"`
should clone the protos branch on a local computer, build a wheel of MDANSE and install it. At the moment, it does not work.

**Describe the expected result**
The final outcome should be that MDANSE package gets built and installed on the machine where the command was executed.

**Describe the actual result**
At the moment, the error message is:
```
Collecting MDANSE
  Cloning https://github.com/ISISNeutronMuon/MDANSE (to revision protos) to /tmp/pip-install-0viif750/mdanse_53ecc0ff727a42f2b1836dfc5db03a5e
  Running command git clone --filter=blob:none --quiet https://github.com/ISISNeutronMuon/MDANSE /tmp/pip-install-0viif750/mdanse_53ecc0ff727a42f2b1836dfc5db03a5e
  Resolved https://github.com/ISISNeutronMuon/MDANSE to commit 78a2958c3413ca1975700fc0b593e979e83085f3
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      Traceback (most recent call last):
        File "/usr/local/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/usr/local/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/local/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-3o3229e_/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-3o3229e_/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-3o3229e_/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 12, in <module>
      ModuleNotFoundError: No module named 'pip'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Suggested fix**
The problem could be originating from:

- requirements.txt
- setup.py
- pyproject.toml
- ...

These should be investigated for possible problems. Typically, `wheel` and `pip` should be defined as parts of the build environment, but not as part of the requirements.

**Additional details**
N/A

**Comment by MBartkowiakSTFC** [comment]
This has now been fixed. It is possible to install MDANSE and MDANSE_GUI directly from GitHub. It is still necessary to install Python Qt bindings manually in case they have not been installed before.
