### ISSUE TITLE
[BUG] MDANSE_GUI crashes when changing the frames options 

### ISSUE THREAD

**Issue by ChiCheng45** [ISISNeutronMuon/MDANSE#299]
**Description of the error**
If you load up a trajectory, open an action dialog and change the frames options MDANSE can crash.

**Describe the actual result**
When changing the options to a number a crash occurs with the error,

```
Traceback (most recent call last):
  File "C:\Users\xcb63893\PycharmProjects\MDANSE\MDANSE_GUI\Src\MDANSE_GUI\InputWidgets\WidgetBase.py", line 102, in updateValue
    self._configurator.configure(current_value)
  File "C:\Users\xcb63893\PycharmProjects\MDANSE\MDANSE\Src\MDANSE\Framework\Configurators\FramesConfigurator.py", line 67, in configure
    self["n_frames"] = self["number"]
                       ~~~~^^^^^^^^^^
```

when changing the option to an empty string I get the error,

```
Traceback (most recent call last):
  File "C:\Users\xcb63893\PycharmProjects\MDANSE\MDANSE_GUI\Src\MDANSE_GUI\InputWidgets\WidgetBase.py", line 101, in updateValue
    current_value = self.get_widget_value()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xcb63893\PycharmProjects\MDANSE\MDANSE_GUI\Src\MDANSE_GUI\InputWidgets\FramesWidget.py", line 69, in get_widget_value
    val = [int(field.text()) for field in self._fields]
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xcb63893\PycharmProjects\MDANSE\MDANSE_GUI\Src\MDANSE_GUI\InputWidgets\FramesWidget.py", line 69, in <listcomp>
    val = [int(field.text()) for field in self._fields]
           ^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: ''
```

**Suggested fix**
It might also be better to change frames to a combobox or something similar so that the user can see what the options are. Or MDANSE should warn the user that there is an issue with their chosen options.

**Comment by MBartkowiakSTFC** [comment]
At the moment, all the input widgets highlight invalid input and do not crash.
