### ISSUE TITLE
[BUG] MDANSE_GUI crashes when loading the same trajectory twice and then deleting one of them

### ISSUE THREAD

**Issue by ChiCheng45** [ISISNeutronMuon/MDANSE#301]
**Description of the error**
MDANSE crashes when loading the same trajectory twice and then deleting one of them. For example,

![image](https://github.com/ISISNeutronMuon/MDANSE/assets/14276033/89db62d3-7aad-494b-ad68-03b260877268)

```
Traceback (most recent call last):
  File "C:\Users\xcb63893\PycharmProjects\MDANSE\MDANSE\Src\MDANSE\Framework\InputData\HDFTrajectoryInputData.py", line 27, in load
    traj = Trajectory(self._name)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xcb63893\PycharmProjects\MDANSE\MDANSE\Src\MDANSE\MolecularDynamics\Trajectory.py", line 53, in __init__
    self._h5_file = h5py.File(self._h5_filename, "r")
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xcb63893\AppData\Local\anaconda3\envs\MDANSE\Lib\site-packages\h5py\_hl\files.py", line 562, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xcb63893\AppData\Local\anaconda3\envs\MDANSE\Lib\site-packages\h5py\_hl\files.py", line 235, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5f.pyx", line 102, in h5py.h5f.open
OSError: Unable to synchronously open file (invalid file name)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\xcb63893\PycharmProjects\MDANSE\MDANSE_GUI\Src\MDANSE_GUI\Tabs\Visualisers\TrajectoryInfo.py", line 20, in visualise_item
    incoming = HDFTrajectoryInputData(fullpath)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xcb63893\PycharmProjects\MDANSE\MDANSE\Src\MDANSE\Framework\InputData\InputFileData.py", line 30, in __init__
    self.load()
  File "C:\Users\xcb63893\PycharmProjects\MDANSE\MDANSE\Src\MDANSE\Framework\InputData\HDFTrajectoryInputData.py", line 29, in load
    raise InputDataError(str(e))
MDANSE.Framework.InputData.IInputData.InputDataError: 'Unable to synchronously open file (invalid file name)'
```

**Comment by ChiCheng45** [comment]
This got fixed in #321.
