### ISSUE TITLE
[BUG] Changing the atom size scaling causes crash with no trajectory loaded.

### ISSUE THREAD

**Issue by ChiCheng45** [ISISNeutronMuon/MDANSE#316]
**Description of the error**
Load the GUI, move to the 3D view tab and change the atom size scaling. MDANSE will then crash with the following error in the logs.

```
Traceback (most recent call last):
  File "C:\Users\xcb63893\PycharmProjects\MDANSE\MDANSE_GUI\Src\MDANSE_GUI\MolecularViewer\Controls.py", line 263, in setAtomSize
    self._viewer._new_scaling(new_value)
  File "C:\Users\xcb63893\PycharmProjects\MDANSE\MDANSE_GUI\Src\MDANSE_GUI\MolecularViewer\MolecularViewer.py", line 152, in _new_scaling
    self.update_renderer()
  File "C:\Users\xcb63893\PycharmProjects\MDANSE\MDANSE_GUI\Src\MDANSE_GUI\MolecularViewer\MolecularViewer.py", line 637, in update_renderer
    self._actors = self.build_scene()
                   ^^^^^^^^^^^^^^^^^^
  File "C:\Users\xcb63893\PycharmProjects\MDANSE\MDANSE_GUI\Src\MDANSE_GUI\MolecularViewer\MolecularViewer.py", line 282, in build_scene
    sphere_mapper.SetScalarRange(self._polydata.GetScalarRange())
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'GetScalarRange'
```

**Describe the expected result**
Should be able to change the value. Then when a trajectory is loaded MDANSE should used that value.

**Comment by ChiCheng45** [comment]
Looks like this got fixed in #347.
