### ISSUE TITLE
[BUG] global motion filtered trajectory job failure.

### ISSUE THREAD

**Issue by ChiCheng45** [ISISNeutronMuon/MDANSE#364]
**Description of the error**
Global motion filtered job fails with the following error.

```
Traceback (most recent call last):
  File "C:\Users\xcb63893\PycharmProjects\MDANSE\MDANSE\Src\MDANSE\Framework\Jobs\IJob.py", line 327, in run
    IJob._runner[mode](self)
  File "C:\Users\xcb63893\PycharmProjects\MDANSE\MDANSE\Src\MDANSE\Framework\Jobs\IJob.py", line 216, in _run_singlecore
    idx, result = self.run_step(index)
                  ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xcb63893\PycharmProjects\MDANSE\MDANSE\Src\MDANSE\Framework\Jobs\GlobalMotionFilteredTrajectory.py", line 135, in run_step
    current_configuration = RealConfiguration(
                            ^^^^^^^^^^^^^^^^^^
TypeError: _Configuration.__init__() takes 3 positional arguments but 4 were given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\xcb63893\AppData\Local\anaconda3\envs\MDANSE5\Lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "C:\Users\xcb63893\PycharmProjects\MDANSE\MDANSE_GUI\Src\MDANSE_GUI\Subprocess\Subprocess.py", line 46, in run
    self._job_instance.run(self._job_parameters)
  File "C:\Users\xcb63893\PycharmProjects\MDANSE\MDANSE\Src\MDANSE\Framework\Jobs\IJob.py", line 335, in run
    raise JobError(self, tb)
MDANSE.Framework.Jobs.IJob.JobError: Traceback (most recent call last):
  File "C:\Users\xcb63893\PycharmProjects\MDANSE\MDANSE\Src\MDANSE\Framework\Jobs\IJob.py", line 327, in run
    IJob._runner[mode](self)
  File "C:\Users\xcb63893\PycharmProjects\MDANSE\MDANSE\Src\MDANSE\Framework\Jobs\IJob.py", line 216, in _run_singlecore
    idx, result = self.run_step(index)
                  ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xcb63893\PycharmProjects\MDANSE\MDANSE\Src\MDANSE\Framework\Jobs\GlobalMotionFilteredTrajectory.py", line 135, in run_step
    current_configuration = RealConfiguration(
                            ^^^^^^^^^^^^^^^^^^
TypeError: _Configuration.__init__() takes 3 positional arguments but 4 were given
```

The DFTB H2O trajectory was used from MDANSE-Examples.

**Comment by MBartkowiakSTFC** [comment]
We removed the global motion filtered trajectory in #1021.
