### ISSUE TITLE
[BUG] VASP trajectory conversion failure

### ISSUE THREAD

**Issue by ChiCheng45** [ISISNeutronMuon/MDANSE#390]
**Description of the error**
VASP trajectory job failure with XDATCAR_900K_Na2Si2O5 from MDANSE test files. The following error is seen.

```Traceback (most recent call last):
  File "C:\Users\xcb63893\PycharmProjects\MDANSE\MDANSE\Src\MDANSE\Framework\Jobs\IJob.py", line 327, in run
    IJob._runner[mode](self)
  File "C:\Users\xcb63893\PycharmProjects\MDANSE\MDANSE\Src\MDANSE\Framework\Jobs\IJob.py", line 216, in _run_singlecore
    idx, result = self.run_step(index)
                  ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xcb63893\PycharmProjects\MDANSE\MDANSE\Src\MDANSE\Framework\Converters\VASP.py", line 111, in run_step
    coords = self._xdatcarFile.read_step(index)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xcb63893\PycharmProjects\MDANSE\MDANSE\Src\MDANSE\Framework\Configurators\XDATCARFileConfigurator.py", line 148, in read_step
    data = np.array(
           ^^^^^^^^^
ValueError: could not convert string to float: b'Direct'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\xcb63893\AppData\Local\anaconda3\envs\MDANSE5\Lib\multiprocessing\process.py", line 314, in _bootstrap
  File "C:\Users\xcb63893\PycharmProjects\MDANSE\MDANSE\Src\MDANSE\Framework\Configurators\XDATCARFileConfigurator.py", line 148, in read_step
    data = np.array(
           ^^^^^^^^^
ValueError: could not convert string to float: b'Direct'
```

**Comment by ChiCheng45** [comment]
turns out that the XDATCAR had too many atoms in one of its timesteps for some reason
