### ISSUE TITLE
BUG: Axis selection broken

### ISSUE THREAD

**Issue by RastislavTuranyi** [ISISNeutronMuon/MDANSE#97]
The Axis selection drop-down menu just shows an empty white box, regardless of whether there are axis selection definitions saved already. This has so far been observed on Windows 10. Below is a picture of how this looks like in the Angular Correlation analysis.
![image](https://user-images.githubusercontent.com/78977041/172568955-5dabfdf8-3740-4510-abf9-34bb0a33af91.png)

The result of this is that the analyses that require Axis selection fail with error like below:

```
c:\users\dni83241\appdata\local\temp\MDANSE_dni8_27308_tqe9tv.pyawfiea -- 26 -- <module> -- ac.run(parameters,status=True)
C:\Users\dni83241\MDANSE\lib\site-packages\mdanse-1.5.0-py2.7-win-amd64.egg\MDANSE\Framework\Jobs\IJob.py -- 326 -- run -- raise JobError(self,tb)
C:\Users\dni83241\MDANSE\lib\site-packages\mdanse-1.5.0-py2.7-win-amd64.egg\MDANSE\Framework\Jobs\IJob.py -- 47 -- __init__ -- tback = traceback.extract_stack()

Traceback (most recent call last):
  File "C:\Users\dni83241\MDANSE\lib\site-packages\mdanse-1.5.0-py2.7-win-amd64.egg\MDANSE\Framework\Jobs\IJob.py", line 302, in run
    self.setup(parameters)
  File "C:\Users\dni83241\MDANSE\lib\site-packages\mdanse-1.5.0-py2.7-win-amd64.egg\MDANSE\Framework\Configurable.py", line 137, in setup
    conf.configure(parameters[name])
  File "C:\Users\dni83241\MDANSE\lib\site-packages\mdanse-1.5.0-py2.7-win-amd64.egg\MDANSE\Framework\Configurators\AtomsListConfigurator.py", line 67, in configure
    molecule,atoms=value
ValueError: need more than 0 values to unpack
```

**Comment by RastislavTuranyi** [comment]
The `AtomsListWidget` works as intended; the reason why it always appears blank is that the created definitions contained the incorrect number of atoms. I will update the User Guide to mention this, and I have opened a PR, #100, which ensures that when a new definition is being made, the user is aware of how many atoms are expected for the analysis they are trying to perform.
