### ISSUE TITLE
BUG: Atom selection not working in Eccentricity analysis

### ISSUE THREAD

**Issue by RastislavTuranyi** [ISISNeutronMuon/MDANSE#98]
Attempting to run the Eccentricity analysis with an atom selection will result in the following error:
```
c:\users\dni83241\appdata\local\temp\MDANSE_dni8_15752_7lvkxo.pyg7iekt -- 26 -- <module> -- ecc.run(parameters,status=True)
C:\Users\dni83241\MDANSE\lib\site-packages\mdanse-1.5.0-py2.7-win-amd64.egg\MDANSE\Framework\Jobs\IJob.py -- 326 -- run -- raise JobError(self,tb)
C:\Users\dni83241\MDANSE\lib\site-packages\mdanse-1.5.0-py2.7-win-amd64.egg\MDANSE\Framework\Jobs\IJob.py -- 47 -- __init__ -- tback = traceback.extract_stack()

Traceback (most recent call last):
  File "C:\Users\dni83241\MDANSE\lib\site-packages\mdanse-1.5.0-py2.7-win-amd64.egg\MDANSE\Framework\Jobs\IJob.py", line 318, in run
    IJob._runner[mode](self)
  File "C:\Users\dni83241\MDANSE\lib\site-packages\mdanse-1.5.0-py2.7-win-amd64.egg\MDANSE\Framework\Jobs\IJob.py", line 223, in _run_monoprocessor
    idx, x = self.run_step(index)
  File "C:\Users\dni83241\MDANSE\lib\site-packages\mdanse-1.5.0-py2.7-win-amd64.egg\MDANSE\Framework\Jobs\Eccentricity.py", line 133, in run_step
    com = center_of_mass(series,masses=self._masses)
  File "C:\Users\dni83241\MDANSE\lib\site-packages\mdanse-1.5.0-py2.7-win-amd64.egg\MDANSE\Mathematics\Geometry.py", line 63, in center_of_mass
    return numpy.average(coords,weights=masses,axis=0)
  File "C:\Users\dni83241\MDANSE\lib\site-packages\numpy\lib\function_base.py", line 413, in average
    "Length of weights not compatible with specified axis.")
ValueError: Length of weights not compatible with specified axis.
```

**Comment by RastislavTuranyi** [comment]
I could not reproduce this bug when the MDANSE was built from source, only when using the installer from the [latest run](https://github.com/ISISNeutronMuon/MDANSE/actions/runs/2370381277). I will wait until #94 is merged into develop, after which I will test again to determine whether this issue arises due to the CI/CD.

**Comment by eurydice76** [comment]
That bug reminds me something. I think that I solved it in the protos branch while I was refactoring this analysis. You can have a look out there.
