### ISSUE TITLE
BUG: Reference basis GUI broken

### ISSUE THREAD

**Issue by RastislavTuranyi** [ISISNeutronMuon/MDANSE#99]
Similar to #97, the reference basis drop-down menu shows a white empty box regardless of whether there is a definition or not.
![image](https://user-images.githubusercontent.com/78977041/172620074-c612e434-47aa-4cdb-a179-626cd2439729.png)

This results in the following trace when attempting to run Spatial Density analysis:
```
c:\users\dni83241\appdata\local\temp\MDANSE_dni8_15752_jvvh39.pyi9rwgs -- 27 -- <module> -- sd.run(parameters,status=True)
C:\Users\dni83241\MDANSE\lib\site-packages\mdanse-1.5.0-py2.7-win-amd64.egg\MDANSE\Framework\Jobs\IJob.py -- 326 -- run -- raise JobError(self,tb)
C:\Users\dni83241\MDANSE\lib\site-packages\mdanse-1.5.0-py2.7-win-amd64.egg\MDANSE\Framework\Jobs\IJob.py -- 47 -- __init__ -- tback = traceback.extract_stack()

Traceback (most recent call last):
  File "C:\Users\dni83241\MDANSE\lib\site-packages\mdanse-1.5.0-py2.7-win-amd64.egg\MDANSE\Framework\Jobs\IJob.py", line 302, in run
    self.setup(parameters)
  File "C:\Users\dni83241\MDANSE\lib\site-packages\mdanse-1.5.0-py2.7-win-amd64.egg\MDANSE\Framework\Configurable.py", line 137, in setup
    conf.configure(parameters[name])
  File "C:\Users\dni83241\MDANSE\lib\site-packages\mdanse-1.5.0-py2.7-win-amd64.egg\MDANSE\Framework\Configurators\AtomsListConfigurator.py", line 67, in configure
    molecule,atoms=value
ValueError: need more than 0 values to unpack
```

**Comment by RastislavTuranyi** [comment]
The `AtomsListWidget` works as intended; the reason why it always appears blank is that the created definitions contained the incorrect number of atoms. I will update the User Guide to mention this, and I have opened a PR, #100, which ensures that when a new definition is being made, the user is aware of how many atoms are expected for the analysis they are trying to perform.

**Comment by RastislavTuranyi** [comment]
The `AtomsListWidget` works as intended; the reason why it always appears blank is that the created definitions contained the incorrect number of atoms. I will update the User Guide to mention this, and I have opened a PR, #100, which ensures that when a new definition is being made, the user is aware of how many atoms are expected for the analysis they are trying to perform.
